version: '3.7'
services:
  kms:
    container_name: kms
    image: kms:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - FLASK_DEBUG=true
      - KMS_KEYRING=/app/kms/privatekey.pem
    restart: always
    networks:
      - network
