version: '3.7'
services:
  kms:
    container_name: kms
    image: kms:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - FLASK_DEBUG=true
      - KMS_KEYRING=/app/kms/vault/privatekey.pem
    restart: always
    ports:
      - "5000:5000"
    networks:
      - kms

networks:
  kms:
    driver: bridge
